feat: реализовал проект с учётом ТЗ
Chernosmaga/java-explore-with-me pull request #1
Opened 2023-12-23 11:47 UTC by Chernosmaga

2023-12-24 08:42 UTC, PolnySkvorets commented on ewm-stats-service/dto/src/main/java/ru/practicum/EndpointHitDto.java
> +    private Integer id;
Не замечание, но ,возможно, что для id Integer будет маловато (обычно берут Long)

2023-12-24 09:16 UTC, PolnySkvorets requested changes
Привет! Оставил несколько комментариев
Отлично

2023-12-24 09:16 UTC, PolnySkvorets commented on ewm-stats-service/service/src/main/java/ru/practicum/mapper/EndpointHitMapper.java
> +    public ViewStatsDto toViewStatsDto(ViewStats viewStats) {
Для этого лучше сделать отдельный маппер. Разделение ответственности

2023-12-24 09:16 UTC, PolnySkvorets commented on ewm-stats-service/service/src/main/java/ru/practicum/mapper/EndpointHitMapper.java
> +                (int) viewStats.getHits());
Лучше такое приведение типов не делать. Сделай не примитив.

2023-12-24 09:16 UTC, PolnySkvorets commented on ewm-stats-service/service/src/main/resources/schema.sql
> +    timestamp timestamp without time zone not null
лучше переименовать имя этого поля в более конкретное

2023-12-25 22:14 UTC, Chernosmaga commented on ewm-stats-service/dto/src/main/java/ru/practicum/EndpointHitDto.java
> +    private Integer id;
Изменил, но должен сказать, что ориентировался на Swagger документацию. Быть может, там ошибка в самой документации, а так согласен полностью, `Long` практичнее 🙂

2023-12-25 22:14 UTC, Chernosmaga commented on ewm-stats-service/service/src/main/java/ru/practicum/mapper/EndpointHitMapper.java
> +                (int) viewStats.getHits());
Исправил, можешь пояснить почему?

2023-12-25 22:18 UTC, Chernosmaga commented on ewm-stats-service/service/src/main/resources/schema.sql
> +    timestamp timestamp without time zone not null
Заменял, после замены падают тесты Postman, потому что там определённое наименование полей, которые в API приходят. Была такая же ситуация: именую булевые значения начиная с `is`, после этого постоянно падают тесты, потому что приходят данные с другим наименованием. Обратился к наставнику с проблемой, ведь учили в Практикуме именно подобным образом именовать методы и поля, тот сказал, что если бы все следовали правилам наименования, жить было бы легче 😄

2023-12-26 22:12 UTC, PolnySkvorets commented on ewm-stats-service/service/src/main/java/ru/practicum/mapper/EndpointHitMapper.java
> +                (int) viewStats.getHits());
Потому что это 1)выглядит странно, что тебе приходится конвертировать 2) относительно затраная операция

2023-12-26 22:13 UTC, PolnySkvorets approved these changes
Принято

2023-12-26 22:16 UTC, merged